### ISSUE TITLE
有没有办法每天提交的次数不同 随机提交几次

### ISSUE THREAD

**Issue by codingories** [justjavac/auto-green#46]
目前的情况是如果设置了某几天提交 那几天提交的次数都是相同的 这样会导致绿的程度一样 看着很假

**Comment by justjavac** [comment]
可以设置每小时运行一次，然后 sleep。

```yaml
name: ci

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          # 在这里随机等一段时间，单位是秒，但是时间不能太长，因为 github actions 有超时时间
          # 也可以用这个随机数做判断，忽略某几次提交
          sleep $((RANDOM % 1000))
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
```
